'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n), num=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(n), pct=n=>n==null?'—':num(n*100)+'%', pp=n=>n==null?'—':(n>0?'+':'')+num(n*100)+' p.p.';
const names=['Resumo Executivo','Perdas Reconhecidas','Vendas','Comparativos','Auditorias · Sobras e Faltas','Perdas Consolidadas','Estoque de Trocas','Importar e Exportar'];
const BASE=window.ZAI_CONFIG?.supabaseUrl||'',KEY=window.ZAI_CONFIG?.publishableKey||'';
let activeStore='',accessibleStores=[],requestVersion=0;
let data=null,page=0,cloud=false,session=null,context=null,pending=null,productPage=0,productQuery='',activeDept='',productStatus='';
function msg(s,error=false){$('#message').innerHTML=s?`<div class="notice ${error?'error':'info'}">${esc(s)}</div>`:''}
function download(filename,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}
function csv(name,headers,rows){const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"';download(name,'\ufeff'+[headers,...rows].map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8')}
async function request(path,body,auth=true){
 if(!BASE||!KEY)throw Error('Configure web/config.js com a URL e a chave publishable do Supabase.');
 if(auth){if(!session)throw Error('Entre na conta para acessar o banco.');if(session.expires_at<Date.now()/1000+60){const r=await request('/auth/v1/token?grant_type=refresh_token',{refresh_token:session.refresh_token},false);session={...r,expires_at:Date.now()/1000+r.expires_in};}}
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),90000);
 try{const r=await fetch(BASE+path,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+session.access_token}:{})},body:JSON.stringify(body),signal:controller.signal});const j=await r.json();if(!r.ok)throw Error(j.message||j.error_description||j.msg||'Falha no Supabase');return j;}catch(e){if(e.name==='AbortError')throw Error('A resposta demorou mais de 90 segundos. Atualize para conferir o estado antes de repetir uma gravação.');throw e}finally{clearTimeout(timer)}
}
function setData(d,isCloud){
 if(d.schema!=='zai-007-v2'||!/^\d{3}$/.test(d.loja)||!Array.isArray(d.perdas)||!d.departamentos||!d.produtos)throw Error('Base analítica incompatível.');
 if(![d.perdas,d.vendas_mensais||[],d.vendas_diarias||[]].every(a=>a.every(r=>Array.isArray(r)&&r.every(x=>typeof x==='string'||typeof x==='number'))))throw Error('Linhas inválidas na base.');
 data=d;cloud=isCloud;pending=null;activeStore=d.loja;syncStores();
 $('#sourceBadge').textContent=isCloud?'Supabase · '+d.loja:'Conferência local · não salva na nuvem';$('#refresh').hidden=!isCloud;$('#logout').hidden=!session;$('#loginOpen').textContent=isCloud?'Conta conectada':'Conectar Supabase';
 $('#dept').innerHTML='<option value="">Todos os departamentos</option>'+Object.entries(data.departamentos).sort((a,b)=>a[1].localeCompare(b[1],'pt-BR')).map(([k,v])=>`<option value="${esc(k)}">${esc(k+' · '+v)}</option>`).join('');
 const months=[...new Set([...(d.perdas||[]).map(r=>r[0].slice(0,7)),...(d.vendas_mensais||[]).map(r=>r[0]),...(d.dias_vendas_completos||[]).map(r=>r.slice(0,7))])].sort();if(months.length){$('#from').value=months.at(-1);$('#to').value=months.at(-1)}render();
}
function card(title,value,note,hero=false){return `<article class="card kpi ${hero?'hero':''}"><label>${esc(title)}</label><b>${value}</b><small>${note}</small></article>`}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map((h,i)=>`<th class="${i?'num':''}">${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>'<tr>'+row.map((x,i)=>`<td class="${i?'num':''}">${x}</td>`).join('')+'</tr>').join(''):`<tr><td colspan="${headers.length}">Sem registros para este filtro.</td></tr>`}</tbody></table></div>`}
function bars(rows,red=false){const max=Math.max(...rows.map(x=>Math.abs(x[1])),1);return rows.length?`<div class="bars">${rows.map(([name,value,label])=>`<div><div class="bar-head"><span>${esc(name)}</span><strong>${label||money(value)}</strong></div><div class="bar-track"><div class="bar-fill ${red?'red':''}" style="width:${Math.max(0,value)/max*100}%"></div></div></div>`).join('')}</div>`:'<p class="small muted">Sem dados comparáveis no período.</p>'}
function trend(){
 const cs=context.months.map(m=>ZAI.select(data,m,m,$('#dept').value)),maxS=Math.max(...cs.map(c=>c.salesTotal),1),maxL=Math.max(...cs.map(c=>c.lossTotal),1);
 // Separate scales explicitly labelled; rate uses a separate comparison table.
 const W=640,H=205,L=70,R=58,T=20,B=37,px=i=>L+(W-L-R)*(cs.length===1?.5:i/(cs.length-1)),py=(v,max)=>H-B-(H-B-T)*v/max;
 const points=(k,max)=>cs.map((c,i)=>k==='salesTotal'&&!c.sales.length?null:[px(i),py(c[k],max)]);
 const poly=(ps,color)=>`<path d="${ps.map((p,i)=>p?((i===0||!ps[i-1])?'M':'L')+p.join(','):'').join(' ')}" fill="none" stroke="${color}" stroke-width="2.5"/>`;
 return `<svg class="trend" viewBox="0 0 ${W} ${H}" role="img" aria-label="Vendas e perdas mensais em reais, com eixos separados">${[0,.5,1].map(t=>`<line x1="${L}" x2="${W-R}" y1="${py(t*maxS,maxS)}" y2="${py(t*maxS,maxS)}" stroke="#e0e8dd"/><text x="${L-8}" y="${py(t*maxS,maxS)+3}" text-anchor="end" font-size="9" fill="#55836d">${num(t*maxS/1000)} mil</text><text x="${W-R+8}" y="${py(t*maxL,maxL)+3}" font-size="9" fill="#bd7750">${num(t*maxL/1000)} mil</text>`).join('')}${poly(points('salesTotal',maxS),'#289575')}${poly(points('lossTotal',maxL),'#c28956')}${cs.map((c,i)=>`${c.sales.length?`<circle cx="${px(i)}" cy="${py(c.salesTotal,maxS)}" r="4" fill="#289575"><title>${c.months[0]}: vendas ${money(c.salesTotal)}, perdas ${money(c.lossTotal)}</title></circle>`:''}<circle cx="${px(i)}" cy="${py(c.lossTotal,maxL)}" r="3" fill="#c28956"/><text x="${px(i)}" y="${H-10}" text-anchor="middle" font-size="10" fill="#6a7d70">${c.months[0].slice(5)}/${c.months[0].slice(2,4)}</text>`).join('')}</svg><div class="legend"><span><i class="dot"></i>Vendas · eixo esquerdo (R$)</span><span><i class="dot" style="background:#c28956"></i>Perdas · eixo direito (R$)</span></div>`;
}
function executive(){const c=context,meta=ZAI.lossTarget(data),rows=ZAI.departmentRows(data,c),top=rows.filter(r=>meta!==null&&r.ratio!==null&&r.ratio>meta).sort((a,b)=>(b.ratio-meta)-(a.ratio-meta)).slice(0,5);
 return `<div class="kpis">${card('Venda total',c.sales.length?money(c.salesTotal):'—','Faturamento da fonte disponível',true)}${card('Perdas reconhecidas',money(c.lossTotal),num(c.loss.length)+' lançamentos')}${card('Perda sobre a venda',pct(c.ratio),'Meta da loja: '+pct(meta)+' · '+(meta===null?'meta não configurada':c.ratio===null?'cobertura insuficiente':pp(c.ratio-meta)))}${card('Atingimento da venda',c.goal&&c.sales.length&&!c.missing.length?pct(c.salesTotal/c.goal):'—','Meta no período: '+money(c.goal))}</div>
 <div class="grid2"><article class="card"><h2>Vendas e perdas no período</h2><p class="desc">Valores monetários mensais. As linhas usam escalas distintas.</p>${trend()}</article><article class="card"><h2>Top 5 · desvio da meta geral</h2><p class="desc">Departamentos acima da meta configurada da loja (${pct(meta)}), ordenados por pontos percentuais.</p>${bars(top.map(r=>[r.name,r.ratio-meta,pp(r.ratio-meta)]),true)}</article></div>
 <div class="kpis">${card('Limite de perdas · '+pct(meta),meta!==null&&c.sales.length?money(c.salesTotal*meta):'—','Sobre as vendas disponíveis')}${card('Excesso sobre o limite',meta!==null&&c.ratio!==null?money(Math.max(0,c.lossTotal-c.salesTotal*meta)):'—','Zero indica resultado dentro da meta')}${card('Média diária de vendas',c.salesDays.size?money(c.salesTotal/c.salesDays.size):'—',num(c.salesDays.size)+' dias cobertos; inclui dias sem movimento')}${card('Distância da meta de vendas',c.goal!=null&&c.sales.length&&!c.missing.length?money(c.salesTotal-c.goal):'—','Realizado menos a meta do período')}</div>
 <article class="card"><h2>Resultado por departamento</h2><p class="desc">Código do departamento une vendas e perdas; inativos permanecem no histórico.</p>${comparisonTable(rows)}</article>`;
}
function comparisonTable(rows){const meta=ZAI.lossTarget(data);return table(['Departamento','Vendas','Perdas','% realizado','Meta setorial','Desvio setorial','Referência geral'],rows.map(r=>[esc(r.code+' · '+r.name),money(r.sales),money(r.loss),r.ratio==null?'—':`<span class="tag ${(r.target??meta)==null?'':r.ratio>(r.target??meta)?'bad':'good'}">${pct(r.ratio)}</span>`,r.target==null?'<span class="muted">Não informada</span>':pct(r.target),r.target==null||r.ratio==null?'—':pp(r.ratio-r.target),pct(meta)]));}
function targets(){return `<details class="card"><summary>Metas de vendas por departamento · base da loja</summary><p class="small muted">Participações definidas sobre o histórico da própria loja. Meta do período: meta diária configurada × dias do período. A base de participação não se recalcula ao filtrar; a configuração deve refletir a operação da unidade.</p>${table(['Departamento','Vendas na base','Participação','Meta diária','Meta no período'],(data.metas||[]).filter(r=>!$('#dept').value||r.codigo===$('#dept').value).sort((a,b)=>b.meta_diaria-a.meta_diaria).map(r=>[esc(r.codigo+' · '+r.descricao),money(r.vendas_historicas),pct(r.participacao),money(ZAI.dailyGoal(data,r.codigo)),money(ZAI.dailyGoal(data,r.codigo)==null?null:ZAI.dailyGoal(data,r.codigo)*context.days)]))}</details>`;}
function sales(){const c=context,w=ZAI.weekdays(data,c,$('#dept').value),r=ZAI.departmentRows(data,c);
 return `<div class="kpis">${card('Faturamento',c.sales.length?money(c.salesTotal):'—','Receita conforme relatório importado',true)}${card('Meta de vendas',money(c.goal),num(c.days)+' dias no período')}${card('Média diária',c.salesDays.size?money(c.salesTotal/c.salesDays.size):'—','Dias cobertos, com ou sem movimento')}${card('SKUs vendidos',num(new Set(c.sales.filter(r=>r[3]!==0||r[4]!==0).map(r=>r[1])).size),'Quantidades separadas por produto; unidades não padronizadas')}</div>
 <div class="grid2"><article class="card"><h2>Vendas por departamento</h2><p class="desc">Top 10 por faturamento.</p>${bars(r.filter(x=>x.sales>0).slice(0,10).map(x=>[x.name,x.sales]))}</article><article class="card"><h2>Média por dia da semana</h2><p class="desc">Somente a base diária. Divisor inclui todos os dias de cada semana com cobertura confirmada.</p>${w.some(x=>x.days)?bars(w.map((x,i)=>[['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'][i]+' · '+x.days+' dias',x.mean||0,money(x.mean)])):'<div class="notice">Aguardando relatório diário íntegro. O histórico mensal não permite calcular segunda, terça etc.</div>'}</article></div>${targets()}
 <div class="section-title"><h2>Departamento → Produto</h2><button id="salesCsv">Exportar produtos CSV</button></div><article class="card"><div class="searchrow"><input id="productSearch" placeholder="Buscar SKU ou produto" value="${esc(productQuery)}"><select id="productStatus"><option value="">Todos os status</option><option>Ativo</option><option>Inativo</option><option>Nao informado</option></select></div><div id="products"></div></article><p class="small muted">Ticket médio indisponível: o relatório não contém quantidade de cupons. Quantidades podem representar unidades ou peso e não são somadas como “itens” entre produtos.</p>`;
}
function products(){const map=new Map();for(const r of context.sales){const key=r[2]+'|'+r[1];if(!map.has(key))map.set(key,{dept:r[2],sku:r[1],qty:0,value:0});let x=map.get(key);x.qty+=r[3];x.value+=r[4]}
 const q=productQuery.toLocaleLowerCase('pt-BR');return [...map.values()].filter(x=>{let p=data.produtos[x.sku]||[x.sku,'Nao informado'];return (!productStatus||p[1]===productStatus)&&(!q||(x.sku+' '+p[0]).toLocaleLowerCase('pt-BR').includes(q))}).sort((a,b)=>b.value-a.value)}
function renderProducts(){const list=products(),size=40,max=Math.max(1,Math.ceil(list.length/size));productPage=Math.min(productPage,max-1);$('#products').innerHTML=table(['Produto / SKU','Departamento','Situação atual','Quantidade¹','Vendas'],list.slice(productPage*size,(productPage+1)*size).map(x=>[esc((data.produtos[x.sku]?.[0]||'Sem descrição')+' · '+x.sku),esc(data.departamentos[x.dept]||x.dept),esc(data.produtos[x.sku]?.[1]||'Nao informado'),num(x.qty),money(x.value)]))+`<div class="actions"><button id="prevProducts" ${productPage===0?'disabled':''}>Anterior</button><span class="small">Página ${productPage+1} / ${max} · ${num(list.length)} produtos/departamentos</span><button id="nextProducts" ${productPage>=max-1?'disabled':''}>Próxima</button></div><p class="small muted">¹ Quantidade na unidade de origem de cada SKU. Situação atual não representa necessariamente o status na data da venda.</p>`;$('#prevProducts').onclick=()=>{productPage--;renderProducts()};$('#nextProducts').onclick=()=>{productPage++;renderProducts()}}
function compare(){const r=ZAI.departmentRows(data,context);return `<div class="kpis">${card('Vendas',context.sales.length?money(context.salesTotal):'—','Mesmo período e departamento',true)}${card('Perdas',money(context.lossTotal),'Perdas reconhecidas')}${card('Perda realizada',pct(context.ratio),'Base de venda positiva e cobertura compatível')}${card('Meta de perdas da loja',pct(ZAI.lossTarget(data)),'Definida conforme comportamento e operação; percentual sobre vendas')}</div><article class="card"><h2>Vendas × perdas × meta</h2><p class="desc">Vermelho: realizado acima da meta setorial. Sem meta setorial, a cor usa a meta configurada da loja. Sem ambas, não há classificação por cor. Nenhuma média simples entre percentuais é usada.</p>${comparisonTable(r)}<div class="actions"><button id="compareCsv">Exportar comparativo CSV</button></div></article><div class="section-title"><h2>Comparação entre competências</h2></div><article class="card">${table(['Competência','Vendas','Perdas','% perda','Meta venda','Atingimento'],context.months.map(m=>{const c=ZAI.select(data,m,m,$('#dept').value);return [m,c.sales.length?money(c.salesTotal):'—',money(c.lossTotal),pct(c.ratio),money(c.goal),c.goal&&c.sales.length&&!c.missing.length?pct(c.salesTotal/c.goal):'—']}))}</article>`;}
function future(){const descriptions={4:['Auditorias de entrada e saída','Receberá sobras e faltas por loja, data, fornecedor, departamento e produto. Os indicadores serão habilitados após a primeira carga conferida.'],5:['Perda consolidada','Faltas + quebras − sobras. Aguardando auditorias para calcular o resultado final e comparar com a venda, sem duplicar as quebras já reconhecidas.'],6:['Estoque de trocas','Receberá fornecedor, SKU, quantidade, valor, data de entrada, prazo e situação. A análise de envelhecimento será habilitada quando houver base.']};let [t,p]=descriptions[page];return `<article class="card empty"><span class="number">0${page+1}</span><p class="eyebrow">AGUARDANDO DADOS</p><h2>${t}</h2><p>${p}</p><span class="pill">Nenhum valor estimado</span></article>`;}
function exchange(){return `<div class="grid2"><article class="card"><h2>Importar relatório</h2><p class="desc">A loja selecionada é aplicada à importação e conferida com o arquivo. Converta o Excel com <b>tools/06_converter_perdas.py</b> e escolha o JSON conferido. Valores ausentes são rejeitados, nunca transformados em zero.</p><label>Tipo de relatório <span aria-hidden="true">*</span><select id="reportType" required><option value="">Selecione antes de escolher o arquivo</option><option value="perdas">Perdas</option><option value="auditorias">Auditorias</option><option value="vendas">Vendas</option><option value="trocas">Trocas</option></select></label><div id="typeGuide" class="notice info">Selecione o tipo de relatório para ver o destino e os requisitos.</div><label>Tipo de atualização<select id="importMode"><option value="complementar">Complementar · preserva registros existentes</option><option value="substituir_dias">Relatório completo · substituir dias presentes</option></select></label><div class="upload"><label>Selecionar JSON conferido<input id="lossFile" type="file" accept=".json" disabled ${!cloud||data?.papel!=='importador'?'disabled':''}></label></div>${!cloud?'<p class="notice">Conecte o Supabase para gravar. A conferência local não atualiza a nuvem.</p>':data?.papel!=='importador'?'<p class="notice">Esta conta possui acesso somente leitura.</p>':''}<div id="importPreview"></div><p class="small muted">No complemento, possíveis coincidências com lançamentos existentes bloqueiam a carga inteira para revisão. Na substituição, os registros anteriores ficam na auditoria do banco.</p></article>
 <article class="card"><h2>Exportar e conferir</h2><p class="desc">A exportação analítica inclui perdas, resumos de vendas, cadastro e metas. O detalhe diário completo fica no banco e no CSV.gz da carga histórica.</p><div class="actions"><button id="backup" ${!data?'disabled':''}>Exportar base analítica JSON</button><button id="goalsCsv" ${!data?'disabled':''}>Exportar metas CSV</button></div><div class="upload"><label>Abrir base para conferência local<input id="localFile" type="file" accept=".json"></label><p class="small muted">Use sua base analítica local ou um backup Z-AI v2. Não substitui o banco nem o backup antigo do navegador.</p></div><p class="small">Carga histórica de vendas diárias: execute <b>tools/09_carregar_diario_historico.py</b>, primeiro em simulação e depois com <b>--commit</b>. Atualização diária de vendas: use o modelo CSV e <b>tools/07_carregar_vendas_diarias.py</b>.</p></article></div>
 <article class="card"><h2>Histórico de importações</h2><p class="desc">${cloud?'Registros persistidos no Supabase':'Histórico incluído no arquivo de conferência'}</p>${table(['Arquivo','Quando','Registros','Valor','Tipo'],(data?.historico||[]).map(r=>[esc(r.file||''),esc(r.when?new Date(r.when).toLocaleString('pt-BR'):''),num(r.rows||0),money(r.value||0),esc(r.tipo||'Backup histórico')]))}</article>`;}
function empty(){return `<article class="card empty"><span class="number">Z</span><h2>Seu painel, conectado às suas lojas</h2><p>Entre na conta do Supabase para consultar os dados salvos. Para conferir esta versão antes da ativação, abra <b>data/base_conferida.json</b> no menu Importar e Exportar.</p><div class="actions" style="justify-content:center"><button class="primary" id="emptyLogin">Conectar Supabase</button><button id="emptyLocal">Abrir base de conferência</button></div></article>`;}
function render(){
 $('#nav').innerHTML=names.map((n,i)=>`<button data-page="${i}" class="${page===i?'active':''}" title="${esc(n)}" aria-label="${esc(n)}" aria-current="${page===i?'page':'false'}"><span class="navicon" aria-hidden="true">${['📊','📉','🛒','⚖️','🔎','🧮','📦','🔄'][i]}</span><span class="navlabel">${n}</span></button>`).join('');$('#nav').querySelectorAll('button').forEach(b=>b.onclick=()=>{page=+b.dataset.page;msg('');render()});
 $('#pageTitle').textContent=names[page];$('#filters').hidden=!data||page>=4;$('#coverage').innerHTML='';$('#stamp').textContent='Consultado em '+new Date().toLocaleString('pt-BR');
 if(data&&page<4){let from=$('#from').value,to=$('#to').value;if(!from||!to||from>to){msg('Informe competências válidas, com início anterior ao fim.',true);return}context=ZAI.select(data,from,to,$('#dept').value);$('#periodNote').textContent=context.days+' dias no período · '+(context.sources.length?context.sources.join(' / '):'vendas não disponíveis');
 const notices=[];if(context.cut)notices.push(page===1?'Perdas: todos os lançamentos da competência. Vendas completas até '+context.cut+'.':'Comparativo acumulado até '+context.cut+'. Vendas, perdas e meta usam os mesmos '+context.days+' dias.');if(context.unmatchedLossCount)notices.push(page===1?num(context.unmatchedLossCount)+' perdas posteriores ao corte de vendas estão incluídas abaixo. Percentual indisponível até completar as vendas.':num(context.unmatchedLossCount)+' perdas posteriores ao corte estão disponíveis em Perdas Reconhecidas; não entram neste comparativo.');if(data.aviso&&!(data.dias_vendas_completos||[]).includes('2026-09-22'))notices.push(data.aviso);if(context.missing.length)notices.push('Vendas ausentes ou incompletas em '+context.missing.join(', ')+'. Percentual de perdas e atingimento não são calculados para o período incompleto.');if(!context.comparable&&!context.missing.length)notices.push('Cobertura de perdas disponível: '+context.first+' a '+context.last+'. O percentual exige cobertura compatível com as vendas de todo o período.');
 $('#coverage').innerHTML=notices.map(s=>`<div class="notice">${esc(s)}</div>`).join('');
 }
 $('#content').innerHTML=page===7?exchange():!data?empty():page===0?executive():page===1?losses():page===2?sales():page===3?compare():future();
 if($('#emptyLogin'))$('#emptyLogin').onclick=()=>$('#login').showModal();if($('#emptyLocal'))$('#emptyLocal').onclick=()=>{page=7;render();$('#localFile').click()};
 if(page===1&&data)bindLossGrid();
 if(page===2&&data){$('#productStatus').value=productStatus;renderProducts();$('#productSearch').oninput=e=>{productQuery=e.target.value;productPage=0;renderProducts()};$('#productStatus').onchange=e=>{productStatus=e.target.value;productPage=0;renderProducts()};$('#salesCsv').onclick=()=>csv('vendas_produtos_'+activeStore+'.csv',['Loja','SKU','Produto','Departamento','Quantidade origem','Vendas'],products().map(x=>[activeStore,x.sku,data.produtos[x.sku]?.[0],x.dept,String(x.qty).replace('.',','),x.value.toFixed(2).replace('.',',')]))}
 if(page===3&&data)$('#compareCsv').onclick=()=>csv('comparativo_'+activeStore+'.csv',['Departamento','Vendas','Perdas','Perda %','Meta setorial %','Meta geral %'],ZAI.departmentRows(data,context).map(r=>[r.name,r.sales.toFixed(2).replace('.',','),r.loss.toFixed(2).replace('.',','),r.ratio==null?'':String(r.ratio*100).replace('.',','),r.target==null?'':String(r.target*100).replace('.',','),ZAI.lossTarget(data)==null?'':String(ZAI.lossTarget(data)*100).replace('.',',')]));
 if(page===7){$('#localFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const d=JSON.parse(await f.text());setData(d,false);msg('Arquivo aberto para conferência. Nenhum dado foi enviado ao banco.')}catch(e){msg(e.message,true)}};$('#backup').onclick=()=>download('Base_Analitica_ZAI_'+activeStore+'_' +new Date().toISOString().slice(0,10)+'.json',JSON.stringify(data));$('#goalsCsv').onclick=()=>csv('metas_'+activeStore+'.csv',['Departamento','Participação %','Meta diaria R$','Meta perdas %'],(data.metas||[]).map(r=>[r.descricao,(r.participacao*100).toFixed(2).replace('.',','),ZAI.dailyGoal(data,r.codigo)==null?'':ZAI.dailyGoal(data,r.codigo).toFixed(2).replace('.',','),r.meta_perda==null?'':(r.meta_perda*100).toFixed(2).replace('.',',')]));$('#lossFile').onchange=e=>previewByType(e.target.files[0]);bindImportType();$('#importMode').onchange=()=>{pending=null;$('#lossFile').value='';$('#importPreview').innerHTML='Selecione novamente o arquivo para conferir este modo.'}}
}
async function preview(file){pending=null;if(!file)return;try{const text=await file.text(),d=JSON.parse(text),rows=ZAI.validateLossImport(d,data),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join(''),dates=new Set(rows.map(r=>r.data)),mode=$('#importMode').value,old=data.perdas.filter(r=>dates.has(r[0])),total=rows.reduce((s,r)=>s+r.valor,0),key=r=>JSON.stringify(r),keys=new Set(old.map(r=>key([r[0],r[1],r[3],r[4]]))),matches=rows.filter(r=>keys.has(key([r.data,r.sku,r.motivo,r.qtde]))).length;
 const blocked=mode==='complementar'&&matches>0;pending={rows,hash,file:file.name,mode,revision:data.revision};$('#importPreview').innerHTML=`<div class="notice ${blocked?'error':''}"><b>Prévia · ${esc(file.name)}</b><br>${num(rows.length)} linhas · ${dates.size} dias · ${money(total)}<br>${mode==='substituir_dias'?num(old.length)+' linhas existentes serão substituídas; valor anterior '+money(ZAI.sum(old,5))+'.':num(matches)+' possíveis coincidências com registros existentes.'}</div>${blocked?'<p>Revise o complemento; nenhuma linha foi importada. Não mude para substituição para contornar coincidências.</p>':`<label style="display:block"><input type="checkbox" id="confirmCheck"> ${mode==='substituir_dias'?'Confirmo que este relatório contém TODOS os lançamentos dos dias presentes.':'Conferi o complemento e seu valor total.'}</label><div class="actions"><button class="primary" id="commitLoss">Confirmar gravação no Supabase</button></div>`}`;if(!blocked)$('#commitLoss').onclick=commit;
 }catch(e){msg(e.message,true);$('#importPreview').innerHTML=''}}
async function commit(){if(!pending||!$('#confirmCheck').checked){msg('Confira a prévia e marque a confirmação antes de gravar.',true);return}const p=pending;$('#commitLoss').disabled=true;try{const r=await request('/rest/v1/rpc/zai_importar_perdas',{p_loja:activeStore,p_revision:p.revision,p_hash:p.hash,p_arquivo:p.file,p_modo:p.mode,p_linhas:p.rows});pending=null;await refresh();msg('Gravado no Supabase: '+num(r.registros)+' registros, '+money(r.valor)+'.');}catch(e){msg(e.message,true);if($('#commitLoss'))$('#commitLoss').disabled=false}}
$('#loginOpen').onclick=()=>$('#login').showModal();$('#loginClose').onclick=()=>$('#login').close();$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='Conectando…';try{const r=await request('/auth/v1/token?grant_type=password',{email:$('#email').value,password:$('#password').value},false);session={...r,expires_at:Date.now()/1000+r.expires_in};$('#password').value='';$('#loginError').textContent='';$('#login').close();await refresh();}catch(e){$('#loginError').textContent=e.message}};
$('#logout').onclick=async()=>{if(session)fetch(BASE+'/auth/v1/logout',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+session.access_token}}).catch(()=>{});requestVersion++;session=null;data=null;cloud=false;context=null;pending=null;activeStore='';accessibleStores=[];syncStores();$('#logout').hidden=true;$('#refresh').hidden=true;$('#sourceBadge').textContent='Sessão encerrada';$('#loginOpen').textContent='Conectar Supabase';msg('');render()};$('#refresh').onclick=()=>refresh();$('#apply').onclick=()=>{productPage=0;render()};